### PR TITLE
Minor fixes and easier development setup

### PR DESCRIPTION
**Pull request by JensKnipper**
I have fixed some small issues concerning SEO and a page title. 
Additionally i have added a docker-compose file which makes development setup easier.

### CODE REVIEW

**Comment by JensKnipper** [comment]
I changed some other stuff to make your template look like this:
https://blog.jensknipper.de/
I added a favicon and a logo, atom feed and added some social links. If you want any of these features just tell me :)

**Review by danurbanowicz — COMMENTED** [review]
Thanks @JensKnipper !

I think outputting the same `site.description` in the head for every page is probably not good SEO, so what do you think about something like:

```
{% if page.section == "home" %}
  <title>{{ site.title }}</title>
  <meta name="description" content="{{ site.description }}">
{% else %}
  <title>{{ page.title | default: site.title }}</title>
  <meta name="description" content="{{ page.description | default: site.description }}">
{% endif %}
```
And then adding `description: [my page description]` to the YAML frontmatter on each page, post etc?

**Comment by JensKnipper** [comment]
You are right about that. Found a nice article about Jekyll SEO and realized my error before you answered:  
https://www.readmodwrite.com/2019-01-18-jekyll-seo-tags/  
  
There is a plugin which sets meta tags for you. It also sets OpenGraph tags.  
For our changes a description is necessary. How do you fell about changing `intro_paragraph` into `description`?
https://github.com/jekyll/jekyll-seo-tag

**Comment by danurbanowicz** [comment]
I don't feel comfortable about adding plugins or dependencies to this template because it's intended to be a very basic and easy-to-understand starter. Of course, developers are free to add their own plugins later as they build out their project.

Right now I think that what is missing is the meta description for SEO, and perhaps only output it if it exists in frontmatter, rather than default to the main site_description for every page i.e. if a relevant description for the page does not exist, don't output a general (sub-optimal) description tag just for the sake of it.

Also, a meta description for SEO purposes might need to be quite different from an intro paragraph on a page; they have different uses. So I think it would be best to stick with a new frontmatter field for the meta description e.g. `meta_description` and maybe output it like this:-

```
{% if page.section == "home" %}
  <title>{{ site.title }}</title>
  <meta name="description" content="{{ site.description }}">
{% else %}
  <title>{{ page.title }}</title>
  {% if page.meta_description %}
    <meta name="description" content="{{ page.meta_description }}">
  {% endif %}
{% endif %}
```

So apart from the home page, it would only output a meta description if one exists in page frontmatter.

What do you think?

**Comment by JensKnipper** [comment]
Sounds good.  
I adjusted the head and added an example in the Frontmatter of a page and a post. I also made them editable via NetlifyCMS.

**Comment by danurbanowicz** [comment]
@JensKnipper BTW I've invited to be a collabrator on this project, if you are interested of course.

Thanks again for your work!

**Pull request merged**
